

name: CI/CD - ECS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ENV: dev
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get ECR URI
        run: |
          echo "ECR_URI=$(aws ecr describe-repositories \
          --repository-names webapp-dev \
          --query 'repositories[0].repositoryUri' \
          --output text)" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build -t webapp:$IMAGE_TAG ./frontend

      - name: Tag Image
        run: |
          docker tag webapp:$IMAGE_TAG $ECR_URI:$IMAGE_TAG

      - name: Push Image
        run: |
          docker push $ECR_URI:$IMAGE_TAG

      # ----------------------------
      # UPDATE TASK DEFINITION
      # ----------------------------
      - name: Register new Task Definition
        id: taskdef
        run: |
          set -e

          NEW_IMAGE="$ECR_URI:$IMAGE_TAG"

          TASK_DEF=$(aws ecs describe-task-definition \
            --task-definition webapp-task-dev)

          echo "$TASK_DEF" | jq --arg IMAGE "$NEW_IMAGE" '
            .taskDefinition
            | .containerDefinitions[0].image = $IMAGE
            | del(
                .taskDefinitionArn,
                .revision,
                .status,
                .requiresAttributes,
                .compatibilities,
                .registeredAt,
                .registeredBy
              )
          ' > new-task-def.json

          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV


      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ecs-cluster-dev \
            --service webapp-service-dev \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment

